### ISSUE TITLE
ChromeAwContentsClientProxy::shouldInterceptRequest

### ISSUE THREAD

**Issue by tankh64** [pwnall/chromeview#1]
chromeview-master/src/us/costan/chrome/impl/ChromeAwContentsClientProxy.java

requires a check on response object

public InterceptedRequestData shouldInterceptRequest(String url) {
    if (viewClient_ != null) {
      WebResourceResponse response =
          viewClient_.shouldInterceptRequest(view_, url);
      if (response != null)
      return new InterceptedRequestData(response.getMimeType(),
          response.getEncoding(), response.getData());
      else
        return null;
    } else {
      return null;
    }
  }

**Comment by pwnall** [comment]
Thank you! I pushed a new version that includes this fix.
