### ISSUE TITLE
Can this support muti-process?

### ISSUE THREAD

**Issue by dzhj11** [pwnall/chromeview#19]
Can this project support muti-process? If it could ,what can I do?
When I modified in AwBrowserProcess.java as follows:
public static void start(final Context context) {
        // We must post to the UI thread to cover the case that the user
        // has invoked Chromium startup by using the (thread-safe)
        // CookieManager rather than creating a WebView.
        ThreadUtils.runOnUiThreadBlocking(new Runnable() {
            @Override
            public void run() {
                try {
                    LibraryLoader.ensureInitialized();
                    AndroidBrowserProcess.init(context,
                            AndroidBrowserProcess.MAX_RENDERERS_AUTOMATIC);
                } catch (ProcessInitException e) {
                    throw new RuntimeException("Cannot initialize WebView", e);
                }
            }
        });
The errors below:
07-17 14:55:54.901: A/chromium(10860): [FATAL:aw_content_browser_client.cc(117)] Check failed: content::RenderProcessHost::run_renderer_in_process(). 
07-17 14:55:54.901: A/libc(10860): Fatal signal 11 (SIGSEGV) at 0xdeadbaad (code=1)

**Comment by dzhj11** [comment]
can anyone help?

**Comment by pwnall** [comment]
@dzhj11 Sorry, I don't plan to make any changes to the Chromium source code outside what it takes to get it running as a WebView. If the Chromium team implements this feature, it will eventually make its way in here.
