### ISSUE TITLE
Failed SharedMemory::Map

### ISSUE THREAD

**Issue by tankh64** [pwnall/chromeview#2]
See https://code.google.com/p/chromium/issues/detail?id=224646

This affects website that has large html. Tried to recompile from the
latest tarball following the instructions outlined in crbuild/vm-build.md
but ended up with a library that exceed 1gig in size. Tried several build
but still unable to have libwebviewchromium.so at just 28mb.

How is this done ? Ninja is already specified with out/Release which
means it must be a release build. Is there another step to strip out
unused functions ?

**Comment by pwnall** [comment]
I'm really just running the commands in the `vm-build.md` file. Maybe you got unlucky and did `gclient sync` at the wrong time?

The issue you mentioned had its fixed committed a few days ago. I just pushed a new build that should include it. Can you give it a try?

Also, right now, only the ARM library is rebuilt. I have an x86 build under way, and I'll re-push when that finishes.

**Comment by pwnall** [comment]
I pushed the x86 build.

**Comment by tankh64** [comment]
Confirmed fixed.

The build I have other than its mega size looks fine but can't be tested as its
crazy to try to transfer 1 gig thru adb.

Will update if I have a solution, don't think its a sync issue. thanks.

**Comment by pwnall** [comment]
Just making this clear, `gclient sync` is the Chromium equivalent of `git pull`. Maybe doing `gclient sync` later today and then re-building will fix the issue. I'm sorry I can't share my VM disk image... it is 42Gb :(

**Comment by tankh64** [comment]
thanks :)
