### ISSUE TITLE
[FATAL:jni_android.cc(139)] Check failed:

### ISSUE THREAD

**Issue by chathudan** [pwnall/chromeview#24]
I'm getting run time error 

[FATAL:jni_android.cc(139)] Check failed: !ClearException(env) && clazz. Failed to find class org/chromium/ui/gfx/SurfaceTextureListener

**Comment by dereky7** [comment]
hi, i meet the same problem, how do you fix it?

**Comment by pwnall** [comment]
This project is not maintained anymore. Look into [the Crosswalk Project](https://crosswalk-project.org/).
