### ISSUE TITLE
network adapters

### ISSUE THREAD

**Issue by 127** [pwnall/chromeview#34]
How is it possible to set both adapters to  virtio-net one of which is NAT and the other is Host-only Adapter o_O?
Taken from https://github.com/pwnall/chromeview/blob/master/crbuild/vm-build.md

**Comment by pwnall** [comment]
virtio-net is the virtual NIC (network card). It's the equivalent of installing two network cards from the same company in one server. I hope this helps.

**Comment by pwnall** [comment]
Also, the instructions here are rather old.

This is the setup I'm trying to use to get some new builds going.
https://github.com/pwnall/chromeview-src/blob/master/doc/vm-setup.md

**Comment by 127** [comment]
I do understand. But it's not possible to tune VM the way described here. Thanks anyway, will check.

**Comment by pwnall** [comment]
Weird, it worked for me. Are you using a recent version of VirtualBox?

![vbox](https://f.cloud.github.com/assets/11460/1169644/dc13bbaa-20b8-11e3-8ce7-0a87e26133ba.png)

**Comment by 127** [comment]
If I do try to set up both as virtio it fails.
