### ISSUE TITLE
No V8 JavaScript engine support?

### ISSUE THREAD

**Issue by yoyeung** [pwnall/chromeview#36]
is it true???

**Comment by pwnall** [comment]
What makes you say that?

**Comment by yoyeung** [comment]
i build the project and run in Nexus 7. The performance not look like a V8 engine. 
I am not sure. So why i need to make it clear.
Thanks

**Comment by pwnall** [comment]
This is an old snapshot of Chromium. The automated packaging process that I set up doesn't work for recent versions, and unfortunately I haven't had time to look into a fix.

**Comment by yoyeung** [comment]
O....it's good. 
Thanks for your reply :+1:
