### ISSUE TITLE
Javascript not working

### ISSUE THREAD

**Issue by cbsol** [pwnall/chromeview#42]
Hey guys,

thanks for this amazing project.

I have a javascript slidingmenu which is not working.
If i slide there is no animation and a white screen overlaps my content.

Any ideas why it is not working ? I cant find the error by debugging.

**Comment by ghost** [comment]
This is very strage issue, but you can enable javascript by calling scrollBy or scrollTo.
All previous touches are executed after scroll..
I can't understand why.

**Comment by cbsol** [comment]
No it works, sorry forgott to close the issue
