### ISSUE TITLE
make: *** [out/target/product/baytrail_generic/obj/SHARED_LIBRARIES/libwebviewchromium_intermediates/LINKED/libwebviewchromium.so] Error 1

### ISSUE THREAD

**Issue by hj91** [pwnall/chromeview#54]
Can i use this library while building an android x86 image?

**Comment by hj91** [comment]
For some reasons (maybe lack of RAM or swap space) this library does not get created in my android build. 

I am planning to include the x86 library in my builds. Hope it works.

**Comment by hj91** [comment]
It works fine.

**Comment by pengkang12** [comment]
i have confront the same question，so i want to know ，how to add x86 library ，thanks

**Comment by hj91** [comment]
@tutudroid if you check your out/target/product/baytrail_generic/obj/SHARED_LIBRARIES/libwebviewchromium_intermediates/LINKED/ then you will find that libwebviewchromium.so is not present in that directory and build process stops.

For that, copy the libwebviewchromium.so from https://github.com/hj91/chromeview/blob/master/libs/x86/libwebviewchromium.so and place it in your out/target/product/baytrail_generic/obj/SHARED_LIBRARIES/libwebviewchromium_intermediates/LINKED/ directory

Start the build process again and you will see the final *.img created in your directory.

Note - i faced this issue while building kitkat image for x86..if you are building for arm processor, refer the file from arm7eabi directory

To avoid this problem, upgrade your test machine with RAM and swap space.

**Comment by lyu90** [comment]
it works.thanks

**Comment by hj91** [comment]
Note -  this library no longer works for Android x86 4.4.4 version.

**Comment by Fumes007** [comment]
I'm having this issue on lollipop 5.1.1 building for arm64
