### ISSUE TITLE
Using Crosswalk or this?

### ISSUE THREAD

**Issue by alexiovay** [pwnall/chromeview#57]
The docu says that this is deprecated and also suggests crosswalk. But this repo seems to be still very active. So I wonder if this should still be used? 
Because I tried for about 3 full days to get Crosswalk working, but there are so many issues where I googled like 24/7 and trying to solve those errors without success after completely removing my old WebView from my app. Also you can't even open issues in the crosswalk project on GitHub, so there's basically no support (only found a mailing list).
So what's the downside of using this library for WebView?

**Comment by pwnall** [comment]
CrossWalk is active -- they have very recent commits, and their Chrome version is a lot more recent than the one included here.

FWIW, Crosswalk does have an issue tracker, but I think you're looking for a user mailing list instead. Issue trackers are intended for folks who want to contribute to a project, and are not the best avenue to get help using the project.

Good luck!
