### ISSUE TITLE
Crosswalk has dead. I hope you could reboot this repo.

### ISSUE THREAD

**Issue by finscn** [pwnall/chromeview#60]
The Crosswalk team said :  https://lists.crosswalk-project.org/pipermail/crosswalk-help/2017-February/002411.html

So I hope you could reboot this repo and make it could used in Cordova .

Thanks

**Comment by pwnall** [comment]
I'm sorry, but I can't justify doing that.

Android L and above let the user specify the WebView supplier, and support having Chrome supply the WebView implementation. Chrome stays up to date, mitigating my original issue of having to deal with each manufacturer's WebView snapshot. Given security issues, it's preferable to write an app using current standards, and rely on Chrome to keep the WebView up to date.

So, the approach behind Crosswalk only benefits ~32% (shrinking) of the Android users. Given that I'm currently on the Chromium team, I think it's better that I spend my time improving the experience of the other ~68% (growing) Android users and all the desktop users. This is why I can't justify rebooting this repository.

FWIW, on the Web platform side, W3C's web-platform-tests project has greatly improved the consistency and compatibility story. Today, getting consistent behavior is a lot easier than it was back when I created this repository.

Sorry. I know this isn't the answer that you're looking for. I hope you'll be able to find a solution that works for you.

**Comment by pwnall** [comment]
I forgot to paste the link with the data behind my 32% / 68% numbers. https://developer.android.com/about/dashboards/index.html

**Comment by finscn** [comment]
the data of https://developer.android.com/about/dashboards/index.html is not truth.
Example , most of  new samsung's android phone used Android 6.0+ .
But the webview is just Chrome 44. 
And the update of samsung's phone never update the chrome webview.

In the Android world , the real situation is very complex.

The statistics of Android 6.0+  is only reference , not truth.

And Most users of smart phone are not geek & IT practitioners , they never try to download/update Android WebView in Google Play by themselves , even don't know how to that.

**Comment by kovel** [comment]
Try to build own, Chromium provides program for embedding https://www.chromium.org/developers/content-module
